// app/blog/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { db } from "@/lib/db";
import { posts } from "@/lib/db/schema";
import { eq, desc } from "drizzle-orm";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Blog",
  description: "Thoughts, articles, and notes by blooshoo",
};

export default async function BlogPage() {
  const allPosts = await db
    .select()
    .from(posts)
    .where(eq(posts.status, "published"))
    .orderBy(desc(posts.createdAt));

  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <div className="content-block">
        <div className="mb-12">
          <h1 className="text-3xl font-bold tracking-tight font-heading">
            Blog
          </h1>
          <p className="text-muted-foreground mt-2">
            Thoughts, articles, and notes.
          </p>
        </div>
        {allPosts.length === 0 ? (
          <div className="text-center py-20">
            <p className="text-muted-foreground text-lg">No posts yet.</p>
            <p className="text-muted-foreground text-sm mt-1">
              Check back soon!
            </p>
          </div>
        ) : (
          <div className="space-y-0">
            {allPosts.map((post) => {
              const tags = JSON.parse(post.tags) as string[];
              return (
                <article
                  key={post.id}
                  className="group border-b border-border last:border-0 py-8 first:pt-0"
                >
                  <Link href={`/blog/${post.slug}`} className="block space-y-3">
                    {post.coverImage && (
                      <div className="relative h-48 rounded-lg overflow-hidden bg-muted mb-4">
                        <Image
                          src={post.coverImage}
                          alt={post.title}
                          fill
                          className="object-cover group-hover:scale-[1.01] transition-transform duration-300"
                          unoptimized
                        />
                      </div>
                    )}
                    <div className="flex items-center gap-2">
                      <time className="text-xs text-muted-foreground">
                        {formatDate(post.createdAt)}
                      </time>
                      {tags.length > 0 && (
                        <>
                          <span className="text-muted-foreground text-xs">
                            ·
                          </span>
                          <div className="flex gap-1 flex-wrap">
                            {tags.map((tag) => (
                              <Badge
                                key={tag}
                                variant="secondary"
                                className="text-xs"
                              >
                                {tag}
                              </Badge>
                            ))}
                          </div>
                        </>
                      )}
                    </div>
                    <h2 className="text-xl font-semibold group-hover:text-primary transition-colors">
                      {post.title}
                    </h2>
                    {post.excerpt && (
                      <p className="text-muted-foreground leading-relaxed line-clamp-2">
                        {post.excerpt}
                      </p>
                    )}
                    <span className="text-sm font-medium inline-flex items-center gap-1 group-hover:gap-2 transition-all">
                      Read more
                      <span aria-hidden>→</span>
                    </span>
                  </Link>
                </article>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

// svelte-app/src/routes/blog/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	let { data } = $props<{ data: PageData }>();

	function formatDate(date: Date | string) {
		return new Date(date).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'long',
			day: 'numeric'
		});
	}
</script>

<svelte:head>
	<title>Blog — blooshoo</title>
	<meta name="description" content="Thoughts, articles, and notes by blooshoo" />
</svelte:head>

<div class="mx-auto max-w-3xl px-4 py-16">
	<div class="content-block">
		<div class="mb-12">
			<h1 class="text-3xl font-bold tracking-tight" style="font-family: var(--font-heading)">
				Blog
			</h1>
			<p class="mt-2 text-slate-400">Thoughts, articles, and notes.</p>
		</div>

		{#if data.posts.length === 0}
			<div class="py-20 text-center">
				<p class="text-lg text-slate-400">No posts yet.</p>
				<p class="mt-1 text-sm text-slate-500">Check back soon!</p>
			</div>
		{:else}
			<div class="space-y-0">
				{#each data.posts as post (post.id)}
					<article class="group border-b border-slate-800/60 py-8 first:pt-0 last:border-0">
						<a href="/blog/{post.slug}" class="block space-y-3">
							{#if post.coverImage}
								<div class="relative mb-4 h-48 overflow-hidden rounded-lg bg-slate-900">
									<img
										src={post.coverImage}
										alt={post.title}
										class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
									/>
								</div>
							{/if}
							<div class="space-y-2">
								<h2
									class="text-xl font-semibold text-slate-200 transition-colors group-hover:text-cyan-400"
									style="font-family: var(--font-heading)"
								>
									{post.title}
								</h2>
								{#if post.excerpt}
									<p class="line-clamp-2 text-sm text-slate-400">{post.excerpt}</p>
								{/if}
								<div class="flex flex-wrap items-center gap-2">
									<time class="text-xs text-slate-500" datetime={new Date(post.createdAt).toISOString()}>
										{formatDate(post.createdAt)}
									</time>
									{#if post.tags.length > 0}
										<span class="text-slate-600">·</span>
										{#each post.tags.slice(0, 4) as tag (tag)}
											<span
												class="rounded-full border border-slate-700/50 bg-slate-800/40 px-2 py-0.5 text-xs text-slate-400"
											>
												{tag}
											</span>
										{/each}
									{/if}
								</div>
							</div>
						</a>
					</article>
				{/each}
			</div>
		{/if}
	</div>
</div>
