// src/lib/components/layout/PublicNav.svelte
<script lang="ts">
	import { page } from '$app/stores';

	const navLinks = [
		{ href: '/', label: 'Home' },
		{ href: '/blog', label: 'Blog' },
		{ href: '/projects', label: 'Projects' },
		{ href: '/contact', label: 'Contact' }
	];

	let menuOpen = $state(false);
	const pathname = $derived($page.url.pathname);

	const menuIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-menu"><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="18" y2="18"/></svg>`;
</script>

<header class="sticky top-0 z-50 border-b border-white/8 content-panel">
	<div class="mx-auto flex h-14 max-w-3xl items-center justify-between px-4">
		<a href="/" aria-label="blooshoo home" class="shrink-0">
			<span class="logo-glitch text-2xl sm:text-3xl">BLOOSHOO</span>
		</a>

		<!-- Desktop nav -->
		<nav class="hidden items-center gap-1 sm:flex">
			{#each navLinks as { href, label } (href)}
				<a
					{href}
					class="nav-link px-3 py-1.5 text-sm font-medium"
					class:text-accent-teal={pathname === href}
				>
					{label}
				</a>
			{/each}
		</nav>

		<!-- Mobile hamburger -->
		<button
			class="btn-ghost px-2 py-1.5 sm:hidden"
			aria-label="Open navigation"
			onclick={() => (menuOpen = !menuOpen)}
		>
			<!-- eslint-disable-next-line svelte/no-at-html-tags -->
			{@html menuIcon}
		</button>
	</div>

	<!-- Mobile menu -->
	{#if menuOpen}
		<nav class="border-t border-white/8 px-4 py-3 sm:hidden">
			<div class="flex flex-col gap-1">
				{#each navLinks as { href, label } (href)}
					<a
						{href}
						class="rounded-md px-3 py-2 text-sm font-medium transition-colors {pathname === href
							? 'bg-accent-teal/10 text-accent-teal'
							: 'text-bloo-muted'}"
						onclick={() => (menuOpen = false)}
					>
						{label}
					</a>
				{/each}
			</div>
		</nav>
	{/if}
</header>

// components/public-nav.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Logo } from "@/components/logo";
import { cn } from "@/lib/utils";

const navLinks = [
  { href: "/", label: "Home" },
  { href: "/blog", label: "Blog" },
  { href: "/projects", label: "Projects" },
  { href: "/contact", label: "Contact" },
];

export function PublicNav() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);

  if (pathname.startsWith("/bloo")) return null;

  return (
    <header className="border-b border-border sticky top-0 z-50">
      <div className="content-panel">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Logo className="shrink-0" />

          {/* Desktop nav */}
          <nav className="hidden sm:flex items-center gap-1">
            {navLinks.map(({ href, label }) => (
              <Link
                key={href}
                href={href}
                className={cn(
                  "nav-link px-3 py-1.5 text-sm font-medium",
                  pathname === href && "text-primary",
                )}
              >
                {label}
              </Link>
            ))}
          </nav>

          {/* Mobile hamburger */}
          <Sheet open={open} onOpenChange={setOpen}>
            <SheetTrigger asChild>
              <Button variant="ghost" size="icon" className="sm:hidden">
                <Menu className="size-5" />
                <span className="sr-only">Open navigation</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="right" className="w-56 p-0 flex flex-col">
              <SheetHeader className="px-4 pt-4 pb-2 border-b border-border">
                <SheetTitle className="text-left text-base font-semibold">
                  Navigation
                </SheetTitle>
              </SheetHeader>
              <nav className="flex flex-col gap-1 p-3">
                {navLinks.map(({ href, label }) => (
                  <Link
                    key={href}
                    href={href}
                    onClick={() => setOpen(false)}
                    className={cn(
                      "flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors",
                      pathname === href
                        ? "bg-primary text-primary-foreground"
                        : "text-muted-foreground hover:bg-accent hover:text-foreground",
                    )}
                  >
                    {label}
                  </Link>
                ))}
              </nav>
            </SheetContent>
          </Sheet>
        </div>
      </div>
    </header>
  );
}
