// src/routes/bloo/login/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { page } from '$app/stores';
	import { authClient } from '$lib/auth-client';
	import type { ActionData } from './$types';

	let { form } = $props<{ form: ActionData }>();

	let discordLoading = $state(false);
	let discordError = $state('');

	// Check for discord error from OAuth callback
	$effect(() => {
		if ($page.url.searchParams.get('error') === 'discord') {
			discordError = 'Discord sign-in failed. Please try again.';
		}
	});

	const discordIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 127.14 96.36" fill="currentColor"><path d="M107.7,8.07A105.15,105.15,0,0,0,81.47,0a72.06,72.06,0,0,0-3.36,6.83A97.68,97.68,0,0,0,49,6.83,72.37,72.37,0,0,0,45.64,0,105.89,105.89,0,0,0,19.39,8.09C2.79,32.65-1.71,56.6.54,80.21h0A105.73,105.73,0,0,0,32.71,96.36,77.7,77.7,0,0,0,39.6,85.25a68.42,68.42,0,0,1-10.85-5.18c.91-.66,1.8-1.34,2.66-2a75.57,75.57,0,0,0,64.32,0c.87.71,1.76,1.39,2.66,2a68.68,68.68,0,0,1-10.87,5.19,77,77,0,0,0,6.89,11.1A105.25,105.25,0,0,0,126.6,80.22h0C129.24,52.84,122.09,29.11,107.7,8.07ZM42.45,65.69C36.18,65.69,31,60,31,53s5-12.74,11.43-12.74S54,46,53.89,53,48.84,65.69,42.45,65.69Zm42.24,0C78.41,65.69,73.25,60,73.25,53s5-12.74,11.44-12.74S96.23,46,96.12,53,91.08,65.69,84.69,65.69Z"/></svg>`;

	async function handleDiscordLogin() {
		discordError = '';
		discordLoading = true;
		try {
			await authClient.signIn.social({
				provider: 'discord',
				callbackURL: '/bloo',
				errorCallbackURL: '/bloo/login?error=discord'
			});
		} catch {
			discordError = 'Discord sign-in failed. Please try again.';
			discordLoading = false;
		}
	}
</script>

<svelte:head>
	<title>Login — bloo</title>
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-slate-950 px-4">
	<div
		class="w-full max-w-sm rounded-xl border border-slate-800/60 bg-slate-900/60 p-8 shadow-login-card backdrop-blur"
	>
		<div class="mb-8 text-center">
			<h1
				class="logo-glitch text-2xl font-bold"
				style="font-family: var(--font-heading)"
				data-text="bloo"
			>
				bloo
			</h1>
			<p class="mt-1 text-sm text-slate-500">Sign in to continue</p>
		</div>

		{#if form?.error || discordError}
			<div
				class="mb-4 rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-3 text-sm text-red-400"
			>
				{form?.error ?? discordError}
			</div>
		{/if}

		<button
			type="button"
			onclick={handleDiscordLogin}
			disabled={discordLoading}
			class="flex w-full items-center justify-center gap-2 rounded-lg border border-slate-700 bg-[#5865F2] px-4 py-2.5 text-sm font-medium text-white transition hover:bg-[#4752C4] disabled:opacity-50"
		>
			<!-- eslint-disable-next-line svelte/no-at-html-tags -->
			{@html discordIcon}
			{discordLoading ? 'Redirecting…' : 'Continue with Discord'}
		</button>

		<div class="relative my-5 flex items-center">
			<div class="flex-grow border-t border-slate-800"></div>
			<span class="mx-3 text-xs text-slate-600">or</span>
			<div class="flex-grow border-t border-slate-800"></div>
		</div>

		<form use:enhance method="POST" class="space-y-5">
			<div class="space-y-2">
				<label class="label-caps" for="email">Email</label>
				<input
					id="email"
					name="email"
					type="email"
					required
					class="input-dark"
					placeholder="you@example.com"
					autocomplete="email"
				/>
			</div>

			<div class="space-y-2">
				<label class="label-caps" for="password">Password</label>
				<input
					id="password"
					name="password"
					type="password"
					required
					class="input-dark"
					placeholder="••••••••"
					autocomplete="current-password"
				/>
			</div>

			<button type="submit" class="btn-cyan w-full justify-center">Sign in</button>
		</form>
	</div>
</div>

// _archive/app/bloo/login/page.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, LogIn } from "lucide-react";
import { createAuthClient } from "better-auth/react";

const authClient = createAuthClient();

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [discordLoading, setDiscordLoading] = useState(false);

  async function handleDiscordLogin() {
    setError("");
    setDiscordLoading(true);
    try {
      await authClient.signIn.social({
        provider: "discord",
        callbackURL: "/bloo",
        errorCallbackURL: "/bloo/login?error=discord",
      });
    } catch {
      setError("Discord sign-in failed. Please try again.");
      setDiscordLoading(false);
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const result = await authClient.signIn.email({
        email,
        password,
        callbackURL: "/bloo",
      });

      if (result && "error" in result && result.error) {
        const err = result.error as { message?: string } | string;
        setError(
          typeof err === "string"
            ? err
            : err.message || "Invalid email or password.",
        );
      } else {
        window.location.href = "/bloo";
      }
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background px-4">
      <div className="w-full max-w-sm">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-foreground tracking-tight">
            blooshoo
          </h1>
          <p className="text-muted-foreground mt-1 text-sm">bloo panel</p>
        </div>

        <Card className="border-border shadow-sm">
          <CardHeader className="pb-4">
            <CardTitle className="text-lg font-semibold">Sign in</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Discord — primary */}
            <Button
              type="button"
              className="w-full gap-2 bg-[#5865F2] hover:bg-[#4752C4] text-white"
              onClick={handleDiscordLogin}
              disabled={discordLoading || loading}
            >
              {discordLoading ? (
                <Loader2 className="animate-spin size-4" />
              ) : (
                <svg
                  className="size-4"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                  aria-hidden="true"
                >
                  <path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057c.002.022.015.043.033.057a19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028 13.979 13.979 0 0 0 1.226-1.994.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03zM8.02 15.33c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.956-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.956 2.418-2.157 2.418zm7.975 0c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.946 2.418-2.157 2.418z" />
                </svg>
              )}
              Sign in with Discord
            </Button>

            {/* Divider */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t border-border" />
              </div>
              <div className="relative flex justify-center text-xs">
                <span className="bg-card px-2 text-muted-foreground">or</span>
              </div>
            </div>

            {/* Email + password */}
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-1.5" suppressHydrationWarning>
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  autoComplete="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  required
                  disabled={loading || discordLoading}
                />
              </div>
              <div className="space-y-1.5" suppressHydrationWarning>
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  autoComplete="current-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  required
                  disabled={loading || discordLoading}
                />
              </div>

              {error && (
                <p className="text-sm text-destructive bg-destructive/10 rounded-md px-3 py-2">
                  {error}
                </p>
              )}

              <Button
                type="submit"
                variant="outline"
                className="w-full"
                disabled={loading || discordLoading}
              >
                {loading ? (
                  <>
                    <Loader2 className="animate-spin size-4" />
                    Signing in…
                  </>
                ) : (
                  <>
                    <LogIn className="size-4" />
                    Sign in with email
                  </>
                )}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
