// src/lib/components/layout/AdminHeader.svelte
<script lang="ts">
	import AdminSidebar from './AdminSidebar.svelte';

	let mobileOpen = $state(false);

	const menuIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-menu"><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="18" y2="18"/></svg>`;

	async function handleLogout() {
		const res = await fetch('/api/auth/sign-out', { method: 'POST' });
		if (res.ok) {
			window.location.href = '/bloo/login';
		}
	}
</script>

<header
	class="flex h-14 shrink-0 items-center gap-4 border-b border-white/8 bg-bloo-card/80 px-4 shadow-topbar backdrop-blur"
>
	<!-- Mobile hamburger -->
	<button
		class="btn-ghost px-2 py-1.5 lg:hidden"
		aria-label="Open navigation"
		onclick={() => (mobileOpen = !mobileOpen)}
	>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		{@html menuIcon}
	</button>

	<span class="font-semibold tracking-tight text-bloo-text">blooshoo admin</span>

	<div class="flex-1"></div>

	<a href="/" class="btn-ghost px-3 py-1.5 text-xs">← View site</a>

	<button class="btn-ghost px-3 py-1.5 text-xs" onclick={handleLogout}>Sign out</button>
</header>

<!-- Mobile drawer overlay -->
{#if mobileOpen}
	<div
		class="fixed inset-0 z-40 bg-black/60 lg:hidden"
		role="button"
		tabindex="-1"
		aria-label="Close navigation"
		onclick={() => (mobileOpen = false)}
		onkeydown={(e) => e.key === 'Escape' && (mobileOpen = false)}
	></div>
	<div
		class="fixed inset-y-0 left-0 z-50 flex w-56 flex-col border-r border-white/8 bg-bloo-card lg:hidden"
	>
		<div class="flex h-14 items-center border-b border-white/8 px-4">
			<span class="font-semibold text-bloo-text">blooshoo admin</span>
		</div>
		<AdminSidebar onNavClick={() => (mobileOpen = false)} />
	</div>
{/if}

// app/bloo/components/admin-header.tsx
"use client";

import { signOut } from "next-auth/react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Menu, LogOut, KeyRound } from "lucide-react";
import { AdminSidebar } from "./admin-sidebar";
import { useState } from "react";

export function AdminHeader() {
  const [open, setOpen] = useState(false);

  return (
    <header className="h-14 border-b border-border bg-card flex items-center px-4 gap-4 shrink-0">
      {/* Mobile hamburger */}
      <Sheet open={open} onOpenChange={setOpen}>
        <SheetTrigger asChild>
          <Button variant="ghost" size="icon" className="lg:hidden">
            <Menu className="size-5" />
            <span className="sr-only">Open navigation</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="w-56 p-0 flex flex-col">
          <SheetHeader className="px-4 pt-4 pb-2 border-b border-border">
            <SheetTitle className="text-left text-base font-semibold">
              blooshoo admin
            </SheetTitle>
          </SheetHeader>
          <AdminSidebar onNavClick={() => setOpen(false)} />
        </SheetContent>
      </Sheet>

      {/* Title */}
      <span className="font-semibold text-foreground tracking-tight">
        blooshoo admin
      </span>

      {/* Spacer */}
      <div className="flex-1" />

      {/* Change password */}
      <Button
        variant="ghost"
        size="sm"
        asChild
        className="text-muted-foreground gap-2"
      >
        <Link href="/bloo/change-password">
          <KeyRound className="size-4" />
          <span className="hidden sm:inline">Password</span>
        </Link>
      </Button>

      {/* Sign out */}
      <Button
        variant="ghost"
        size="sm"
        className="text-muted-foreground gap-2"
        onClick={() => signOut({ callbackUrl: "/bloo/login" })}
      >
        <LogOut className="size-4" />
        <span className="hidden sm:inline">Sign out</span>
      </Button>
    </header>
  );
}
