// src/routes/bloo/media/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData } from './$types';

	let { data } = $props<{ data: PageData }>();

	function formatSize(bytes: number) {
		if (bytes < 1024) return `${bytes} B`;
		if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
		return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
	}

	function formatDate(date: Date | string) {
		return new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
	}

	let uploadError = $state('');
	let uploading = $state(false);

	async function handleUpload(e: Event) {
		const form = e.target as HTMLFormElement;
		const formData = new FormData(form);
		uploading = true;
		uploadError = '';

		try {
			const res = await fetch('/api/media/upload', { method: 'POST', body: formData });
			if (!res.ok) {
				const json = await res.json().catch(() => ({}));
				uploadError = json.error ?? 'Upload failed';
			} else {
				form.reset();
				// Reload to show new file
				window.location.reload();
			}
		} catch {
			uploadError = 'Upload failed';
		} finally {
			uploading = false;
		}
	}
</script>

<svelte:head>
	<title>Media — bloo</title>
</svelte:head>

<div class="space-y-6">
	<h1 class="text-2xl font-bold text-slate-100" style="font-family: var(--font-heading)">Media</h1>

	<!-- Upload form -->
	<div class="rounded-lg border border-slate-800/60 bg-slate-900/40 p-4">
		<h2 class="mb-3 text-sm font-semibold text-slate-300">Upload file</h2>
		{#if uploadError}
			<div class="mb-3 rounded border border-red-500/30 bg-red-500/5 px-3 py-2 text-xs text-red-400">
				{uploadError}
			</div>
		{/if}
		<form onsubmit={handleUpload} class="flex items-center gap-3">
			<input type="file" name="file" required class="input-dark text-sm" />
			<button type="submit" class="btn-cyan shrink-0" disabled={uploading}>
				{uploading ? 'Uploading…' : 'Upload'}
			</button>
		</form>
	</div>

	{#if data.media.length === 0}
		<div class="rounded-lg border border-slate-800/60 bg-slate-900/40 py-20 text-center">
			<p class="text-slate-400">No media files yet.</p>
		</div>
	{:else}
		<div class="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
			{#each data.media as item (item.id)}
				<div class="group relative overflow-hidden rounded-lg border border-slate-800/60 bg-slate-900/40">
					{#if item.mimeType.startsWith('image/')}
						<img src={item.url} alt={item.filename} class="h-32 w-full object-cover" />
					{:else}
						<div class="flex h-32 items-center justify-center">
							<span class="text-xs text-slate-500">{item.mimeType}</span>
						</div>
					{/if}
					<div class="p-3">
						<p class="truncate text-xs font-medium text-slate-300">{item.filename}</p>
						<div class="mt-1 flex items-center justify-between">
							<span class="text-xs text-slate-500">{formatSize(item.size)}</span>
							<span class="text-xs text-slate-500">{formatDate(item.createdAt)}</span>
						</div>
						<div class="mt-2 flex gap-2">
							<a
								href={item.url}
								target="_blank"
								rel="noopener noreferrer"
								class="text-xs text-cyan-400 hover:underline"
							>
								View
							</a>
							<button
								onclick={() => navigator.clipboard.writeText(item.url)}
								class="text-xs text-slate-400 hover:text-slate-200"
							>
								Copy URL
							</button>
							<form method="POST" action="?/delete" use:enhance class="ml-auto">
								<input type="hidden" name="id" value={item.id} />
								<button
									type="submit"
									class="text-xs text-red-400 hover:text-red-300"
									onclick={(e) => {
										if (!confirm('Delete this file?')) e.preventDefault();
									}}
								>
									Delete
								</button>
							</form>
						</div>
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

// _archive/app/bloo/media/page.tsx
"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Loader2,
  Upload,
  Trash2,
  Copy,
  Check,
  FileImage,
  File,
} from "lucide-react";
import type { Media } from "@/lib/db/schema";

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function isImage(mimeType: string) {
  return mimeType.startsWith("image/");
}

export default function MediaPage() {
  const [mediaItems, setMediaItems] = useState<Media[]>([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [deletingId, setDeletingId] = useState<number | null>(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState<number | null>(null);
  const [copiedId, setCopiedId] = useState<number | null>(null);
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const fetchMedia = useCallback(async () => {
    try {
      const res = await fetch("/api/media");
      const data = await res.json();
      setMediaItems(data);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchMedia();
  }, [fetchMedia]);

  async function uploadFile(file: File) {
    setUploading(true);
    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch("/api/media/upload", {
        method: "POST",
        body: formData,
      });

      if (res.ok) {
        await fetchMedia();
      }
    } finally {
      setUploading(false);
    }
  }

  async function handleFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    const files = e.target.files;
    if (!files) return;
    for (const file of Array.from(files)) {
      await uploadFile(file);
    }
    e.target.value = "";
  }

  async function handleDelete(id: number) {
    setDeletingId(id);
    try {
      await fetch(`/api/media/${id}`, { method: "DELETE" });
      setMediaItems((prev) => prev.filter((m) => m.id !== id));
    } finally {
      setDeletingId(null);
      setConfirmDeleteId(null);
    }
  }

  function handleCopy(item: Media) {
    navigator.clipboard.writeText(item.url).then(() => {
      setCopiedId(item.id);
      setTimeout(() => setCopiedId(null), 2000);
    });
  }

  function handleDragOver(e: React.DragEvent) {
    e.preventDefault();
    setDragActive(true);
  }

  function handleDragLeave(e: React.DragEvent) {
    e.preventDefault();
    setDragActive(false);
  }

  async function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    setDragActive(false);
    const files = Array.from(e.dataTransfer.files);
    for (const file of files) {
      await uploadFile(file);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Media</h1>
          <p className="text-muted-foreground text-sm mt-1">
            {mediaItems.length} file{mediaItems.length !== 1 ? "s" : ""}{" "}
            uploaded
          </p>
        </div>
        <div className="flex gap-2">
          <input
            ref={fileInputRef}
            type="file"
            multiple
            accept="image/*,video/*,.pdf,.txt,.md"
            className="hidden"
            onChange={handleFileInput}
          />
          <Button
            onClick={() => fileInputRef.current?.click()}
            disabled={uploading}
          >
            {uploading ? (
              <Loader2 className="animate-spin size-4" />
            ) : (
              <Upload className="size-4" />
            )}
            Upload
          </Button>
        </div>
      </div>

      {/* Drop zone */}
      <div
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
        className={`border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-colors ${
          dragActive
            ? "border-primary bg-primary/5"
            : "border-border hover:border-primary/50 hover:bg-muted/50"
        }`}
      >
        {uploading ? (
          <div className="flex flex-col items-center gap-2 text-muted-foreground">
            <Loader2 className="animate-spin size-8" />
            <p className="text-sm font-medium">Uploading…</p>
          </div>
        ) : (
          <div className="flex flex-col items-center gap-2 text-muted-foreground">
            <Upload className="size-8" />
            <p className="text-sm font-medium">
              {dragActive
                ? "Drop files here"
                : "Click or drag and drop files to upload"}
            </p>
            <p className="text-xs">Images, PDFs, and other files</p>
          </div>
        )}
      </div>

      {loading ? (
        <div className="flex justify-center py-16">
          <Loader2 className="animate-spin size-6 text-muted-foreground" />
        </div>
      ) : mediaItems.length === 0 ? (
        <div className="text-center py-8 text-muted-foreground">
          <p className="text-sm">No files uploaded yet.</p>
        </div>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          {mediaItems.map((item) => (
            <div
              key={item.id}
              className="group relative border border-border rounded-lg overflow-hidden bg-card"
            >
              {/* Preview */}
              <div className="aspect-square bg-muted flex items-center justify-center overflow-hidden">
                {isImage(item.mimeType) ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={item.url}
                    alt={item.originalName}
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <div className="flex flex-col items-center gap-1 text-muted-foreground p-2">
                    {item.mimeType.startsWith("image/") ? (
                      <FileImage className="size-8" />
                    ) : (
                      <File className="size-8" />
                    )}
                    <span className="text-xs text-center truncate w-full px-1">
                      {item.mimeType.split("/")[1]?.toUpperCase() ?? "FILE"}
                    </span>
                  </div>
                )}
              </div>

              {/* Info */}
              <div className="p-2 space-y-1">
                <p
                  className="text-xs font-medium text-foreground truncate"
                  title={item.originalName}
                >
                  {item.originalName}
                </p>
                <p className="text-xs text-muted-foreground">
                  {formatBytes(item.size)}
                </p>
              </div>

              {/* Actions */}
              <div className="flex items-center gap-1 px-2 pb-2">
                <Button
                  variant="ghost"
                  size="sm"
                  className="flex-1 text-xs gap-1 h-7"
                  onClick={() => handleCopy(item)}
                >
                  {copiedId === item.id ? (
                    <Check className="size-3 text-green-500" />
                  ) : (
                    <Copy className="size-3" />
                  )}
                  {copiedId === item.id ? "Copied" : "Copy URL"}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-destructive hover:text-destructive hover:bg-destructive/10 h-7 w-7 p-0"
                  onClick={() => setConfirmDeleteId(item.id)}
                  disabled={deletingId === item.id}
                >
                  {deletingId === item.id ? (
                    <Loader2 className="size-3 animate-spin" />
                  ) : (
                    <Trash2 className="size-3" />
                  )}
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Confirm delete dialog */}
      <Dialog
        open={confirmDeleteId !== null}
        onOpenChange={(open) => !open && setConfirmDeleteId(null)}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete file?</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            This will permanently delete the file from BunnyCDN and remove it
            from the database. This action cannot be undone.
          </p>
          <div className="flex justify-end gap-2 mt-2">
            <Button
              variant="outline"
              onClick={() => setConfirmDeleteId(null)}
              disabled={deletingId !== null}
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={() =>
                confirmDeleteId !== null && handleDelete(confirmDeleteId)
              }
              disabled={deletingId !== null}
            >
              {deletingId !== null ? (
                <Loader2 className="animate-spin size-4" />
              ) : (
                "Delete"
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
